# Generated by ChatGPT

import sys
import re
import urllib.parse

def transform_javascript(input_file, output_file):
    with open(input_file, 'r') as f:
        content = f.read()

    # Remove single line comments starting at the beginning of the line
    content = re.sub(r'^\s*\/\/.*', '', content, flags=re.MULTILINE)

    # Remove all newline characters
    content = content.replace('\n', '')

    # Replace double quotes with single quotes
    content = content.replace('"', '\'')

    transformed_lines = []
    for line in content.split(';'):
        # Remove consecutive spaces
        line = ' '.join(line.split())
        transformed_lines.append(line.strip())
    
    urlencoded_js = urllib.parse.quote(';'.join(transformed_lines))

    bookmarklet_script = 'javascript: (() => {%s})();'%(urlencoded_js)

    with open(output_file, 'r') as f:
        html = f.read()

    final_html = re.sub(r'<a href="[^"]*" onclick="return false;">GPSH</a>','<a href="{}" onclick="return false;">GPSH</a>'.format(bookmarklet_script), html)

    with open(output_file, 'w') as f:
        f.write(final_html)
    
if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python script.py input_file.js")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = "index.html"

    transform_javascript(input_file, output_file)
    print("Transformation complete. Transformed file saved as:", output_file)