name: Generate Bookmarklet and Update Index HTML
inputs:
  name:
    description: 'Artifact name'
    required: false
    default: 'github-pages'

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run bookmarkify.py
      run: |
        python bookmarkify.py github-search-helper.js

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add index.html
        git commit -m "Update bookmarklet in index.html"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

    - name: Upload artifact
      id: upload-artifact
      working-directory: ${{ github.workspace }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ./index.html
        if-no-files-found: error