name: Generate Bookmarklet and Update Index HTML

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run bookmarkify.py
      run: |
        pip install --upgrade pip
        python bookmarkify.py github-search-helper.js > bookmarklet.txt

    - name: Read bookmarklet.txt
      id: read-bookmarklet
      run: echo "::set-output name=bookmarklet::$(cat bookmarklet.txt)"

    - name: Update index.html
      working-directory: ${{ github.workspace }}
      run: |
        pwd
        ls
        sed -i -e 's|<a href="[^"]*" onclick="return false;">GPSH</a>|<a href="THIS IS A TEST" onclick="return false;">GPSH</a>|g' index.html

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add index.html
        git commit -m "Update bookmarklet in index.html"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

  deploy-pages:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Dummy step
      run: echo "This is a dummy step for GitHub Pages deployment"